name: Mod Build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Download MSBuild installer
      run: powershell "$source = (New-Object System.Net.WebClient).DownloadString(\"https://gist.githubusercontent.com/sgkoishi/87e613881f9164bf03849603dd4f4266/raw/\") ; Add-Type
        -TypeDefinition \"$source\" ; [SetupMSBuild]::Download((Get-Item -Path \".\\\").FullName);
        "
    - name: Setup .NET SDK
      run: start /i /wait vs_BuildTools.exe --add "Microsoft.VisualStudio.Workload.ManagedDesktopBuildTools" -p --wait --installPath "%cd%\VSBuildTools" --norestart --nocache
    - name: Download tModLoader
      run: powershell "$source = (New-Object System.Net.WebClient).DownloadString(\"https://gist.githubusercontent.com/sgkoishi/f80d3b59973f8499383d215cd747ad74/raw/\") ; $references = (\"System.IO.Compression.FileSystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\", \"Microsoft.CSharp, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\"); Add-Type -ReferencedAssemblies $references -TypeDefinition \"$source\" ; [SetupModLoader]::Download((Get-Item -Path \".\\\").FullName);
        "
    - name: Install XNA
      run: start /i /wait xnafx40_redist.msi /passive /norestart
    - name: Release build
      run: '"%cd%\VSBuildTools\MSBuild\Current\Bin\MSBuild.exe" /restore Localizer.sln /p:Configuration=Release /p:Platform=x86'
    - name: Packaging
      run: '".\\build-mod-release.bat"'
    - name: Clean artifact
      run: |
        mkdir .\Artifact\Artifact\
        copy "%USERPROFILE%\Documents\My Games\Terraria\ModLoader\Mods\" .\Artifact\Artifact
        del Artifact\Artifact\enabled.json
    - uses: actions/upload-artifact@master
      with:
        name: Build Artifact
        path: Artifact