name: Mod Build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install NuGet client
        uses: warrenbuckley/Setup-Nuget@v1
      - name: Download tModLoader
        run: |
          $source = (New-Object System.Net.WebClient).DownloadString("https://gist.githubusercontent.com/sgkoishi/f80d3b59973f8499383d215cd747ad74/raw/");
          $references = (
            "Microsoft.CSharp, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a",
            "System.IO, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a",
            "System.IO.Compression, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089",
            "System.IO.Compression.FileSystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089",
            "System.Reflection, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a",
            "System.Runtime.Extensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a",
            "System.Text.RegularExpressions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"
          );
          Add-Type -ReferencedAssemblies $references -TypeDefinition "$source";
          [SetupModLoader]::Download((Get-Item -Path ".\").FullName);
      - name: Install XNA
        run: start /i /wait xnafx40_redist.msi /passive /norestart
      - name: Release build
        run: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe" Localizer.sln /p:Configuration=Release /p:Platform=x86'
      - name: Packaging
        run: '".\\build-mod-release.bat"'
      - name: Clean artifact
        run: |
          mkdir .\Artifact\Artifact\
          copy "%USERPROFILE%\Documents\My Games\Terraria\ModLoader\Mods\" .\Artifact\Artifact
          del Artifact\Artifact\enabled.json
      - uses: actions/upload-artifact@master
        with:
          name: Build Artifact
          path: Artifact