name: Mod Build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install NuGet client
        uses: warrenbuckley/Setup-Nuget@v1

      - name: Setup tModLoader
        uses: chi-rei-den/SetupModLoader@v1

      - name: Restore NuGet Packages
        run: nuget restore Localizer.sln

      - name: Release build
        run: '& "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe" Localizer.sln /p:Configuration=Release /p:Platform=x86'

      - name: Packaging
        run: '& ".\\build-mod-release.bat"'

      - name: Clean artifact
        run: |
          mkdir .\Artifact\Artifact\
          Copy-Item -Path "$ENV:UserProfile\Documents\My Games\Terraria\ModLoader\Mods\*" -Destination .\Artifact\Artifact
          del .\Artifact\Artifact\enabled.json

      - uses: actions/upload-artifact@master
        with:
          name: Build Artifact
          path: Artifact